apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
    backstage.io/techdocs-ref: dir:.
  name: legacy-system-A
spec:
  lifecycle: production
  owner: my-team
  type: service